package enums

type Collections string

const (
	Collections_Accounts                       Collections = "Accounts"
	Collections_AgreementsToTermsAndConditions Collections = "AgreementsToTermsAndConditions"
	Collections_AirNetworksProvinces           Collections = "AirNetworksProvinces"
	Collections_Audios                         Collections = "Audios"
	Collections_AutoProvisionReferences        Collections = "AutoProvisionReferences"
	Collections_BlackListPhoneNumbers          Collections = "BlackListPhoneNumbers"
	Collections_Calls                          Collections = "Calls"
	Collections_CallerIdMasks                  Collections = "CallerIdMasks"
	Collections_CallFlows                      Collections = "CallFlows"
	Collections_CloudServices                  Collections = "CloudServices"
	Collections_Contacts                       Collections = "Contacts"
	Collections_CustomerInfos                  Collections = "CustomerInfos"
	Collections_Extensions                     Collections = "Extensions"
	Collections_FaxEmailInfos                  Collections = "FaxEmailInfos"
	Collections_FaxesIncoming                  Collections = "FaxesIncoming"
	Collections_FaxOutgoingGroups              Collections = "FaxOutgoingGroups"
	Collections_Voicemails                     Collections = "Voicemails"
	Collections_Identities                     Collections = "Identities"
	Collections_IPs                            Collections = "IPs"
	Collections_LineKeyGroups                  Collections = "LineKeyGroups"
	Collections_LogWebServiceRequests          Collections = "LogWebServiceRequests"
	Collections_MusicOnHoldGroups              Collections = "MusicOnHoldGroups"
	Collections_Phones                         Collections = "Phones"
	Collections_PhoneConfigurations            Collections = "PhoneConfigurations"
	Collections_PowerDialerGroups              Collections = "PowerDialerGroups"
	Collections_SMS                            Collections = "SMS"
	Collections_TrunkOriginations              Collections = "TrunkOriginations"
	Collections_TrunkTerminations              Collections = "TrunkTerminations"
	Collections_TrunkTerminationGroups         Collections = "TrunkTerminationGroups"
	Collections_VoipNumbers                    Collections = "VoipNumbers"
	Collections_VoipProviders                  Collections = "VoipProviders"
	Collections_WebHooks                       Collections = "WebHooks"
	Collections_UnauthorizedTokens             Collections = "UnauthorizedTokens"
)
